library verilog;
use verilog.vl_types.all;
entity picorv32_axi is
    generic(
        ENABLE_COUNTERS : vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_COUNTERS64: vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_REGS_16_31: vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_REGS_DUALPORT: vl_logic_vector(0 downto 0) := (others => Hi1);
        TWO_STAGE_SHIFT : vl_logic_vector(0 downto 0) := (others => Hi1);
        BARREL_SHIFTER  : vl_logic_vector(0 downto 0) := (others => Hi0);
        TWO_CYCLE_COMPARE: vl_logic_vector(0 downto 0) := (others => Hi0);
        TWO_CYCLE_ALU   : vl_logic_vector(0 downto 0) := (others => Hi0);
        COMPRESSED_ISA  : vl_logic_vector(0 downto 0) := (others => Hi0);
        CATCH_MISALIGN  : vl_logic_vector(0 downto 0) := (others => Hi1);
        CATCH_ILLINSN   : vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_PCPI     : vl_logic_vector(0 downto 0) := (others => Hi0);
        ENABLE_MUL      : vl_logic_vector(0 downto 0) := (others => Hi0);
        ENABLE_FAST_MUL : vl_logic_vector(0 downto 0) := (others => Hi0);
        ENABLE_DIV      : vl_logic_vector(0 downto 0) := (others => Hi0);
        ENABLE_IRQ      : vl_logic_vector(0 downto 0) := (others => Hi0);
        ENABLE_IRQ_QREGS: vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_IRQ_TIMER: vl_logic_vector(0 downto 0) := (others => Hi1);
        ENABLE_TRACE    : vl_logic_vector(0 downto 0) := (others => Hi0);
        REGS_INIT_ZERO  : vl_logic_vector(0 downto 0) := (others => Hi0);
        MASKED_IRQ      : vl_logic_vector(31 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        LATCHED_IRQ     : vl_logic_vector(31 downto 0) := (Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1);
        PROGADDR_RESET  : vl_logic_vector(31 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        PROGADDR_IRQ    : vl_logic_vector(31 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0);
        STACKADDR       : vl_logic_vector(31 downto 0) := (Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1)
    );
    port(
        clk             : in     vl_logic;
        resetn          : in     vl_logic;
        trap            : out    vl_logic;
        mem_axi_awvalid : out    vl_logic;
        mem_axi_awready : in     vl_logic;
        mem_axi_awaddr  : out    vl_logic_vector(31 downto 0);
        mem_axi_awprot  : out    vl_logic_vector(2 downto 0);
        mem_axi_wvalid  : out    vl_logic;
        mem_axi_wready  : in     vl_logic;
        mem_axi_wdata   : out    vl_logic_vector(31 downto 0);
        mem_axi_wstrb   : out    vl_logic_vector(3 downto 0);
        mem_axi_bvalid  : in     vl_logic;
        mem_axi_bready  : out    vl_logic;
        mem_axi_arvalid : out    vl_logic;
        mem_axi_arready : in     vl_logic;
        mem_axi_araddr  : out    vl_logic_vector(31 downto 0);
        mem_axi_arprot  : out    vl_logic_vector(2 downto 0);
        mem_axi_rvalid  : in     vl_logic;
        mem_axi_rready  : out    vl_logic;
        mem_axi_rdata   : in     vl_logic_vector(31 downto 0);
        pcpi_valid      : out    vl_logic;
        pcpi_insn       : out    vl_logic_vector(31 downto 0);
        pcpi_rs1        : out    vl_logic_vector(31 downto 0);
        pcpi_rs2        : out    vl_logic_vector(31 downto 0);
        pcpi_wr         : in     vl_logic;
        pcpi_rd         : in     vl_logic_vector(31 downto 0);
        pcpi_wait       : in     vl_logic;
        pcpi_ready      : in     vl_logic;
        irq             : in     vl_logic_vector(31 downto 0);
        eoi             : out    vl_logic_vector(31 downto 0);
        trace_valid     : out    vl_logic;
        trace_data      : out    vl_logic_vector(35 downto 0)
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of ENABLE_COUNTERS : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_COUNTERS64 : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_REGS_16_31 : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_REGS_DUALPORT : constant is 2;
    attribute mti_svvh_generic_type of TWO_STAGE_SHIFT : constant is 2;
    attribute mti_svvh_generic_type of BARREL_SHIFTER : constant is 2;
    attribute mti_svvh_generic_type of TWO_CYCLE_COMPARE : constant is 2;
    attribute mti_svvh_generic_type of TWO_CYCLE_ALU : constant is 2;
    attribute mti_svvh_generic_type of COMPRESSED_ISA : constant is 2;
    attribute mti_svvh_generic_type of CATCH_MISALIGN : constant is 2;
    attribute mti_svvh_generic_type of CATCH_ILLINSN : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_PCPI : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_MUL : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_FAST_MUL : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_DIV : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_IRQ : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_IRQ_QREGS : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_IRQ_TIMER : constant is 2;
    attribute mti_svvh_generic_type of ENABLE_TRACE : constant is 2;
    attribute mti_svvh_generic_type of REGS_INIT_ZERO : constant is 2;
    attribute mti_svvh_generic_type of MASKED_IRQ : constant is 2;
    attribute mti_svvh_generic_type of LATCHED_IRQ : constant is 2;
    attribute mti_svvh_generic_type of PROGADDR_RESET : constant is 2;
    attribute mti_svvh_generic_type of PROGADDR_IRQ : constant is 2;
    attribute mti_svvh_generic_type of STACKADDR : constant is 2;
end picorv32_axi;
